-- MySQL Script generated by MySQL Workbench
-- Thu Oct  9 08:16:11 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ll_capstone_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ll_capstone_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ll_capstone_db` DEFAULT CHARACTER SET utf8mb3 ;
USE `ll_capstone_db` ;

-- -----------------------------------------------------
-- Table `ll_capstone_db`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ll_capstone_db`.`customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `customer_phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ll_capstone_db`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ll_capstone_db`.`bookings` (
  `booking_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `booking_time` DATETIME NOT NULL,
  `arrival_time` DATETIME NULL DEFAULT NULL,
  `num_guests` INT NOT NULL,
  PRIMARY KEY (`booking_id`),
  INDEX `customer_id_fk_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `customer_id_fk`
    FOREIGN KEY (`customer_id`)
    REFERENCES `ll_capstone_db`.`customers` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ll_capstone_db`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ll_capstone_db`.`menu` (
  `menu_id` INT NOT NULL AUTO_INCREMENT,
  `menu_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`menu_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ll_capstone_db`.`menu_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ll_capstone_db`.`menu_items` (
  `menu_item_id` INT NOT NULL AUTO_INCREMENT,
  `menu_id` INT NOT NULL,
  `item_name` VARCHAR(100) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `cuisine` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`menu_item_id`),
  INDEX `menu_id_fk_idx` (`menu_id` ASC) VISIBLE,
  CONSTRAINT `menu_id_fk`
    FOREIGN KEY (`menu_id`)
    REFERENCES `ll_capstone_db`.`menu` (`menu_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ll_capstone_db`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ll_capstone_db`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `order_date` DATETIME NOT NULL,
  `table_num` INT NOT NULL,
  `payment_status` TINYINT NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `customer_id_fk2_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `customer_id_fk2`
    FOREIGN KEY (`customer_id`)
    REFERENCES `ll_capstone_db`.`customers` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ll_capstone_db`.`order_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ll_capstone_db`.`order_details` (
  `order_detail_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `menu_item_id` INT NOT NULL,
  `price_at_order` DECIMAL(10,2) NOT NULL,
  `quantity` INT NOT NULL,
  `notes` VARCHAR(255) NULL DEFAULT NULL,
  INDEX `order_id_fk2_idx` (`order_id` ASC) VISIBLE,
  INDEX `menu_item_id_fk` (`menu_item_id` ASC) VISIBLE,
  PRIMARY KEY (`order_detail_id`),
  CONSTRAINT `menu_item_id_fk`
    FOREIGN KEY (`menu_item_id`)
    REFERENCES `ll_capstone_db`.`menu_items` (`menu_item_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `order_id_fk2`
    FOREIGN KEY (`order_id`)
    REFERENCES `ll_capstone_db`.`orders` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ll_capstone_db`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ll_capstone_db`.`staff` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `position` VARCHAR(255) NOT NULL,
  `hired_on_date` DATE NOT NULL,
  `termination_date` DATE NOT NULL,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ll_capstone_db`.`order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ll_capstone_db`.`order_status` (
  `order_status_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `time_updated` DATETIME NOT NULL,
  `current_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`order_status_id`),
  INDEX `order_id_fk_idx` (`order_id` ASC) VISIBLE,
  INDEX `employee_id_fk_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `employee_id_fk`
    FOREIGN KEY (`employee_id`)
    REFERENCES `ll_capstone_db`.`staff` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `order_id_fk`
    FOREIGN KEY (`order_id`)
    REFERENCES `ll_capstone_db`.`orders` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

USE `ll_capstone_db` ;

-- -----------------------------------------------------
-- Placeholder table for view `ll_capstone_db`.`orders_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ll_capstone_db`.`orders_view` (`order_id` INT, `quantity` INT, `price_at_order` INT);

-- -----------------------------------------------------
-- View `ll_capstone_db`.`orders_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ll_capstone_db`.`orders_view`;
USE `ll_capstone_db`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`LL_admin`@`%` SQL SECURITY DEFINER VIEW `ll_capstone_db`.`orders_view` AS select `ll_capstone_db`.`order_details`.`order_id` AS `order_id`,`ll_capstone_db`.`order_details`.`quantity` AS `quantity`,`ll_capstone_db`.`order_details`.`price_at_order` AS `price_at_order` from `ll_capstone_db`.`order_details` where (`ll_capstone_db`.`order_details`.`quantity` > 2);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;